Transform: AWS::Serverless-2016-10-31
Description: |
  An AWS Serverless Application.

Parameters:
  LambdaFunctionRole:
    Type: String
    Description: Role that used for lambda function.

  DirectoryCode:
    Type: String
    Description: Name of this repository.

Resources:
  ServerlessApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServerlessApi From Stack ${AWS::StackName}
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MainFunction.Arn}/invocations
              responses: {}
      EndpointConfiguration:
        Type: REGIONAL
      TracingEnabled: true
  
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: ServerlessLambda6
      CodeUri:
        Bucket: artifact-bucket-gh128
        Key: !Sub ${DirectoryCode}/code.zip
      Handler: ServerlessLambda6::ServerlessLambda6.Functions::Main
      Role: !Sub ${LambdaFunctionRole}
      Runtime: dotnet6
      MemorySize: 128
      Timeout: 3
      Tracing: Active
      Events:
        ServerlessApiGET:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref ServerlessApi
