AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  An AWS Serverless Application.

Parameters:
  LambdaFunctionRole:
    Type: String
    Description: Role that used for lambda function.
  DirectoryCode:
    Type: String
    Description: Name of this repository.

Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ServerlessLambda6-Cloudformation
      Description: Serverless lambda function with dotnet runtime
      Handler: ServerlessLambda6::ServerlessLambda6.Functions::Main
      Runtime: dotnet6
      Role: !Sub ${LambdaFunctionRole}
      CodeUri:
        Bucket: artifact-bucket-gh128
        Key: !Sub ${DirectoryCode}/code.zip
      Events:
        MainGet:
          Type: Api
          Properties:
            Path: "/get"
            Method: GET

Outputs:
  ApiGetURL:
    Description: API endpoint URL for Prod environment
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get/

  LambdaARN:
    Description: ARN lambda function
    Value: !GetAtt MainFunction.Arn
